### PR TITLE
New UX

### PR DESCRIPTION
**Pull request by simkim**

### CODE REVIEW

**Comment by simkim** [comment]
must fix at least #16 and #17 to deploy

**Comment by genezys** [comment]
My fork auto-deploys to https://dlcenter-develop.herokuapp.com/.

If you have a Heroku account, I may be able to transfer the ownership to you so that you can auto-deploy your branch instead of my fork.

**Comment by simkim** [comment]
heroku account is "squadracer"

**Comment by genezys** [comment]
I am only able to transfer ownership to a Team account that I am a member of...

Another solution is you to completely recreate the pipeline. This is simple as Heroku default settings work great for this project.

**Pull request merged**
